---- Insert dummy authors
--INSERT INTO author (name, bio) VALUES ('Jane Austen', 'English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the 18th century.');
--INSERT INTO author (name, bio) VALUES ('Leo Tolstoy', 'Russian writer who is regarded as one of the greatest authors of all time.');
--INSERT INTO author (name, bio) VALUES ('J.K. Rowling', 'British author, screenwriter, producer, and philanthropist. She is best known for writing the Harry Potter fantasy series.');
--
---- Insert dummy books
--INSERT INTO book (title, author_id) VALUES ('Pride and Prejudice', 1);
--INSERT INTO book (title, author_id) VALUES ('War and Peace', 2);
--INSERT INTO book (title, author_id) VALUES ('Harry Potter and the Philosopher''s Stone', 3);
